### ISSUE TITLE
Implementar pagina do meu perfil

### ISSUE THREAD

**Issue by luckened** [luckened/my-steam-app#4]
![image](https://user-images.githubusercontent.com/42002892/123345463-82858d80-d52c-11eb-9a07-3bbaf31d251d.png)

**Comment by rgomesms** [comment]
Lembre-se de atualizar com a nova versão da página. No canto direito a opção de edição e na parte de baixo os jogos favoritos

![Desktop - 5](https://user-images.githubusercontent.com/42679354/124526076-fd299500-ddd7-11eb-80b9-166a7bc889ea.png)
